import {
  Home,
  Activity,
  AlertTriangle,
  Shield,
  Link as LinkIcon,
  Bot,
  Receipt,
  Users,
  Code,
  Webhook,
  Settings,
  Plus,
  Sun,
  Moon,
  PowerOff,
  ScrollText,
  Radar,
} from "lucide-react";
import type { Command } from "./types";

const iconProps = { size: 14, strokeWidth: 1.75 } as const;

export const COMMANDS: Command[] = [
  // ─── NAVIGATE ───────────────────────────────────────────
  {
    id: "nav-home",
    title: "Go to Home",
    subtitle: "Overview and metrics",
    section: "navigate",
    icon: <Home {...iconProps} />,
    shortcut: ["g", "h"],
    keywords: ["dashboard", "overview", "metrics"],
    run: ({ router }) => router.push("/home"),
  },
  {
    id: "nav-actions",
    title: "Go to Actions",
    subtitle: "Proposed, approved, and executed actions",
    section: "navigate",
    icon: <Activity {...iconProps} />,
    shortcut: ["g", "a"],
    keywords: ["history", "ledger", "executions"],
    run: ({ router }) => router.push("/actions"),
  },
  {
    id: "nav-escalations",
    title: "Go to Escalations",
    subtitle: "Actions awaiting human review",
    section: "navigate",
    icon: <AlertTriangle {...iconProps} />,
    shortcut: ["g", "e"],
    keywords: ["inbox", "pending", "review"],
    run: ({ router }) => router.push("/escalations"),
  },
  {
    id: "nav-policies",
    title: "Go to Policies",
    subtitle: "Rules and policy evaluator",
    section: "navigate",
    icon: <Shield {...iconProps} />,
    shortcut: ["g", "p"],
    keywords: ["rules", "governance"],
    run: ({ router }) => router.push("/policies"),
  },
  {
    id: "nav-adapters",
    title: "Go to Adapters",
    subtitle: "Integration adapters",
    section: "navigate",
    icon: <LinkIcon {...iconProps} />,
    shortcut: ["g", "c"],
    keywords: ["connectors", "integrations"],
    run: ({ router }) => router.push("/adapters"),
  },
  {
    id: "nav-agents",
    title: "Go to Agents",
    subtitle: "Registered and observed agents",
    section: "navigate",
    icon: <Bot {...iconProps} />,
    keywords: ["bots", "workers"],
    run: ({ router }) => router.push("/agents"),
  },
  {
    id: "nav-entities",
    title: "Go to Entities",
    subtitle: "Business entities and their action history",
    section: "navigate",
    icon: <Users {...iconProps} />,
    keywords: ["users", "customers", "objects"],
    run: ({ router }) => router.push("/entities"),
  },
  {
    id: "nav-receipts",
    title: "Go to Receipts",
    subtitle: "Tamper-evident audit trail",
    section: "navigate",
    icon: <Receipt {...iconProps} />,
    keywords: ["audit", "ledger", "hash"],
    run: ({ router }) => router.push("/receipts"),
  },
  {
    id: "nav-events",
    title: "Go to Events",
    subtitle: "Raw event stream",
    section: "navigate",
    icon: <ScrollText {...iconProps} />,
    keywords: ["logs", "stream", "telemetry"],
    run: ({ router }) => router.push("/events"),
  },
  {
    id: "nav-threat-logs",
    title: "Go to Threat Logs",
    subtitle: "Security events and anomalies",
    section: "navigate",
    icon: <Radar {...iconProps} />,
    keywords: ["security", "anomalies", "alerts"],
    run: ({ router }) => router.push("/threat-logs"),
  },
  {
    id: "nav-kill-switch",
    title: "Go to Kill Switch",
    subtitle: "Emergency halt controls",
    section: "navigate",
    icon: <PowerOff {...iconProps} />,
    keywords: ["emergency", "halt", "pause"],
    run: ({ router }) => router.push("/kill-switch"),
  },
  {
    id: "nav-webhooks",
    title: "Go to Webhooks",
    subtitle: "Outbound event delivery",
    section: "navigate",
    icon: <Webhook {...iconProps} />,
    keywords: ["notifications", "delivery"],
    run: ({ router }) => router.push("/webhooks"),
  },
  {
    id: "nav-team",
    title: "Go to Team",
    subtitle: "Members and permissions",
    section: "navigate",
    icon: <Users {...iconProps} />,
    keywords: ["members", "users", "access"],
    run: ({ router }) => router.push("/team"),
  },
  {
    id: "nav-developers",
    title: "Go to Developers",
    subtitle: "API keys and SDKs",
    section: "navigate",
    icon: <Code {...iconProps} />,
    keywords: ["keys", "tokens", "api", "sdk"],
    run: ({ router }) => router.push("/developers"),
  },
  {
    id: "nav-settings",
    title: "Go to Settings",
    subtitle: "Workspace configuration",
    section: "navigate",
    icon: <Settings {...iconProps} />,
    keywords: ["config", "preferences", "workspace"],
    run: ({ router }) => router.push("/settings"),
  },

  // ─── CREATE ─────────────────────────────────────────────
  {
    id: "create-policy",
    title: "New Policy Rule",
    section: "create",
    icon: <Plus {...iconProps} />,
    shortcut: ["c", "p"],
    keywords: ["add", "rule"],
    run: ({ router }) => router.push("/policies?new=1"),
  },
  {
    id: "create-agent",
    title: "Register Agent",
    section: "create",
    icon: <Plus {...iconProps} />,
    shortcut: ["c", "a"],
    keywords: ["add", "bot", "register"],
    run: ({ router }) => router.push("/agents?new=1"),
  },
  {
    id: "create-connector",
    title: "Add Connector",
    section: "create",
    icon: <Plus {...iconProps} />,
    shortcut: ["c", "c"],
    keywords: ["integration", "adapter"],
    run: ({ router }) => router.push("/adapters?new=1"),
  },
  {
    id: "create-webhook",
    title: "New Webhook",
    section: "create",
    icon: <Plus {...iconProps} />,
    keywords: ["add", "notification"],
    run: ({ router }) => router.push("/webhooks?new=1"),
  },
  {
    id: "create-api-key",
    title: "Generate API Key",
    section: "create",
    icon: <Plus {...iconProps} />,
    keywords: ["token", "credential"],
    run: ({ router }) => router.push("/developers?new=1"),
  },

  // ─── THEME ──────────────────────────────────────────────
  {
    id: "theme-toggle-dark",
    title: "Switch to Dark Mode",
    section: "theme",
    icon: <Moon {...iconProps} />,
    keywords: ["theme", "dark", "night"],
    run: ({ toggleTheme }) => toggleTheme(),
    when: () =>
      typeof document !== "undefined" &&
      document.documentElement.getAttribute("data-theme") === "light",
  },
  {
    id: "theme-toggle-light",
    title: "Switch to Light Mode",
    section: "theme",
    icon: <Sun {...iconProps} />,
    keywords: ["theme", "light", "day"],
    run: ({ toggleTheme }) => toggleTheme(),
    when: () =>
      typeof document === "undefined" ||
      document.documentElement.getAttribute("data-theme") !== "light",
  },
];
